name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: List contents
        run: ls -R      

      - name: Sync only the public HTML files
        run: |
          aws s3 cp ModiSonFrontEnd/Views/Home/Index.html s3://modison-bucket/index.html
          aws s3 cp ModiSonFrontEnd/Views/Home/Privacy.html s3://modison-bucket/privacy.html

      - name: Sync static assets
        run: aws s3 sync ModiSonFrontEnd/wwwroot s3://modison-bucket --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2MA2BW9PESS66 --paths "/*"